# Generated by Django 4.1.7 on 2023-02-23 10:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishingHouse',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70, unique=True)),
                ('books', models.ManyToManyField(blank=True, to='book.book')),
            ],
        ),
    ]
