# Generated by Django 4.1.7 on 2023-02-23 10:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70, unique=True)),
                ('type', models.CharField(choices=[('Kryminał', 'Kryminał'), ('Dramat', 'Dramat'), ('Pamiętnik', 'Pamiętnik'), ('Romans', 'Romans'), ('Dla dzieci', 'Dla dzieci'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Sci-Fi', 'Sci-Fi'), ('Powieść historyczna', 'Powieść historyczna'), ('Bibliografia', 'Bibliografia'), ('Reportaż', 'Reportaż'), ('Powieść młodzieżowa', 'Powieść młodzieżowa'), ('Poradnik', 'Poradnik'), ('Kucharska', 'Kucharska')], max_length=150)),
            ],
        ),
    ]
