# Generated by Django 4.1.7 on 2023-02-23 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publishing_house', '0001_initial'),
        ('bookstore', '0001_initial'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookstores',
            field=models.ManyToManyField(blank=True, to='bookstore.bookstore'),
        ),
        migrations.AddField(
            model_name='book',
            name='publishing_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publishing_house.publishinghouse'),
        ),
    ]
